from Preprocessing.Preprocessing import PreprocessingStep

from Preprocessing.Denoising import Denoising
from Preprocessing.Binarization import Binarization
from Preprocessing.Deskewing import Deskewing